[build]
  base = "frontend/client"
  command = "npm run build:netlify"
  publish = "frontend/client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"
