[build]
base = "frontend/client"
command = "npm install --no-workspaces && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
